"""Integration tests for ``maverick flight-plan`` CLI commands.

T014: End-to-end tests covering the full create-then-validate workflow.
These tests verify that the create and validate subcommands work together
correctly in realistic scenarios, using isolated temporary filesystems.
"""

from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner

from maverick.main import cli


class TestCreateThenValidateWorkflow:
    """Full workflow: create a plan then validate it."""

    def test_create_then_validate_skeleton_passes(self) -> None:
        """Creating a plan then validating the unedited skeleton exits 0.

        The skeleton generated by ``generate_skeleton`` satisfies all V1-V9
        validation rules, so an unedited file should pass validation.
        """
        runner = CliRunner()
        with runner.isolated_filesystem():
            # Step 1: create the flight plan
            result_create = runner.invoke(cli, ["flight-plan", "create", "test-plan"])
            assert result_create.exit_code == 0, (
                f"Create failed. Output: {result_create.output!r}"
            )

            # Step 2: verify the file was created
            plan_path = Path(".maverick/flight-plans/test-plan.md")
            assert plan_path.exists(), f"Expected file at {plan_path}"

            # Step 3: validate the skeleton
            result_validate = runner.invoke(
                cli, ["flight-plan", "validate", str(plan_path)]
            )
            assert result_validate.exit_code == 0, (
                f"Validate failed for skeleton. Output: {result_validate.output!r}"
            )

    def test_create_then_validate_shows_success_message(self) -> None:
        """Both create and validate print success messages for valid workflows."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            runner.invoke(cli, ["flight-plan", "create", "my-plan"])
            plan_path = Path(".maverick/flight-plans/my-plan.md")

            result = runner.invoke(cli, ["flight-plan", "validate", str(plan_path)])
            assert result.exit_code == 0
            output_lower = result.output.lower()
            assert any(
                word in output_lower for word in ("valid", "passed", "ok", "success")
            ), f"Expected success message in output: {result.output!r}"

    def test_create_with_custom_output_dir_then_validate(self) -> None:
        """Create in custom dir, then validate the created file."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            custom_dir = "my-plans"
            result_create = runner.invoke(
                cli,
                ["flight-plan", "create", "api-feature", "--output-dir", custom_dir],
            )
            assert result_create.exit_code == 0, (
                f"Create failed. Output: {result_create.output!r}"
            )

            plan_path = Path(custom_dir) / "api-feature.md"
            assert plan_path.exists(), f"Expected file at {plan_path}"

            result_validate = runner.invoke(
                cli, ["flight-plan", "validate", str(plan_path)]
            )
            assert result_validate.exit_code == 0, (
                f"Validate failed. Output: {result_validate.output!r}"
            )

    def test_edited_plan_with_real_content_passes_validation(self) -> None:
        """A plan edited to have real (non-placeholder) content also passes."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            # Create then replace with real content
            runner.invoke(cli, ["flight-plan", "create", "real-plan"])
            plan_path = Path(".maverick/flight-plans/real-plan.md")

            real_content = """\
---
name: real-plan
version: "1"
created: 2026-02-28
tags: []
---

## Objective
Implement the real-plan feature with full integration.

## Success Criteria
- [ ] Feature is implemented
- [x] Tests pass

## Scope

### In
- The core feature implementation

### Out
- Legacy system integration

### Boundaries
- Only affects the new module

## Context
This is a real flight plan for testing purposes.

## Constraints
- Must not break existing tests

## Notes
- Created for integration testing
"""
            plan_path.write_text(real_content, encoding="utf-8")

            result_validate = runner.invoke(
                cli, ["flight-plan", "validate", str(plan_path)]
            )
            assert result_validate.exit_code == 0, (
                f"Expected valid. Output: {result_validate.output!r}"
            )


class TestCreateFailures:
    """create subcommand failure modes in integration context."""

    def test_invalid_name_fails_with_exit_code_1(self) -> None:
        """Invalid kebab-case name exits 1 without creating any file."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            result = runner.invoke(cli, ["flight-plan", "create", "Invalid Name"])
            assert result.exit_code == 1
            # No file should be created
            plan_dir = Path(".maverick/flight-plans")
            if plan_dir.exists():
                assert list(plan_dir.glob("*.md")) == []

    def test_duplicate_create_fails_with_exit_code_1(self) -> None:
        """Creating a plan that already exists exits 1."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            # First create succeeds
            result1 = runner.invoke(cli, ["flight-plan", "create", "duplicate-plan"])
            assert result1.exit_code == 0

            # Second create fails (overwrite guard)
            result2 = runner.invoke(cli, ["flight-plan", "create", "duplicate-plan"])
            assert result2.exit_code == 1

    def test_multiple_plans_can_be_created(self) -> None:
        """Multiple plans with different names can coexist."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            for name in ["plan-alpha", "plan-beta", "plan-gamma"]:
                result = runner.invoke(cli, ["flight-plan", "create", name])
                assert result.exit_code == 0, (
                    f"Failed to create plan '{name}'. Output: {result.output!r}"
                )

            plan_dir = Path(".maverick/flight-plans")
            created_files = sorted(plan_dir.glob("*.md"))
            assert len(created_files) == 3


class TestValidateFailures:
    """validate subcommand failure modes in integration context."""

    def test_nonexistent_file_fails_with_exit_code_1(self) -> None:
        """Validating a non-existent file exits 1."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            result = runner.invoke(
                cli,
                ["flight-plan", "validate", ".maverick/flight-plans/ghost.md"],
            )
            assert result.exit_code == 1
            output_lower = result.output.lower()
            assert any(
                word in output_lower for word in ("not found", "error", "no such")
            ), f"Expected error message, got: {result.output!r}"

    def test_file_missing_frontmatter_fails(self) -> None:
        """Validating a file with no YAML frontmatter exits 1."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            plan_path = Path("bad-plan.md")
            plan_path.write_text(
                "# No Frontmatter Here\n\nJust plain markdown.\n",
                encoding="utf-8",
            )
            result = runner.invoke(cli, ["flight-plan", "validate", str(plan_path)])
            assert result.exit_code == 1

    def test_file_missing_required_sections_fails(self) -> None:
        """A file with valid frontmatter but missing sections exits 1."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            plan_path = Path("incomplete-plan.md")
            plan_path.write_text(
                '---\nname: incomplete\nversion: "1"\ncreated: 2026-02-28\n---\n\n'
                "# No required sections here\n",
                encoding="utf-8",
            )
            result = runner.invoke(cli, ["flight-plan", "validate", str(plan_path)])
            assert result.exit_code == 1

    def test_validate_reports_specific_issues(self) -> None:
        """Validation output lists the specific issues found."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            # File missing the 'name' frontmatter field
            plan_path = Path("missing-name.md")
            plan_path.write_text(
                '---\nversion: "1"\ncreated: 2026-02-28\n---\n\n'
                "## Objective\n\nSome objective.\n\n"
                "## Success Criteria\n\n- [ ] Criterion\n\n"
                "## Scope\n\n### In\n\n- Item\n",
                encoding="utf-8",
            )
            result = runner.invoke(cli, ["flight-plan", "validate", str(plan_path)])
            assert result.exit_code == 1
            # Should mention 'name' field issue
            assert "name" in result.output.lower() or "V4" in result.output
