from __future__ import annotations

# Re-export WorkflowHistoryEntry for backwards compatibility
from maverick.tui.history import WorkflowHistoryEntry
from maverick.tui.models.dialogs import (
    ConfirmDialogConfig,
    ErrorDialogConfig,
    InputDialogConfig,
)
from maverick.tui.models.enums import (
    BranchValidationStatus,
    CheckStatus,
    FindingSeverity,
    IssueSeverity,
    IterationStatus,
    MessageType,
    ProcessingMode,
    PRState,
    ReviewAction,
    SettingType,
    SidebarMode,
    StageStatus,
    StreamChunkType,
    ValidationStepStatus,
)
from maverick.tui.models.findings import (
    CodeContext,
    CodeLocation,
    FixResult,
    ReviewFinding,
    ReviewFindingItem,
    ReviewIssue,
)
from maverick.tui.models.github import (
    GitHubIssue,
    IssueSelectionItem,
    PRInfo,
    StatusCheck,
)
from maverick.tui.models.navigation import (
    NavigationContext,
    NavigationEntry,
    NavigationItem,
    SidebarState,
)
from maverick.tui.models.screen_state import (
    ConfigScreenState,
    HomeScreenState,
    ReviewScreenActionState,
    ReviewScreenState,
    ScreenState,
    SettingsScreenState,
    WorkflowScreenState,
)
from maverick.tui.models.settings import (
    ConfigOption,
    SettingDefinition,
    SettingsSection,
    SettingValue,
)
from maverick.tui.models.theme import (
    ACCENT_COLORS,
    DARK_THEME,
    LIGHT_THEME,
    THEMES,
    AccentColor,
    ThemeColors,
    ThemeManager,
    ThemeMode,
    ThemePreferences,
    get_current_theme,
    get_theme_manager,
)
from maverick.tui.models.widget_state import (
    AgentOutputState,
    AgentStreamEntry,
    LogEntry,
    LogPanelState,
    LoopIterationItem,
    LoopIterationState,
    PRSummaryState,
    ReviewFindingsState,
    StreamingPanelState,
    ValidationStatusState,
    WorkflowProgressState,
)
from maverick.tui.models.workflow import (
    AgentMessage,
    BranchValidation,
    RecentWorkflowEntry,
    RefuelResultItem,
    StageState,
    ToolCallInfo,
    ValidationStep,
    WorkflowStage,
)

__all__ = [
    # Enums
    "BranchValidationStatus",
    "CheckStatus",
    "FindingSeverity",
    "IssueSeverity",
    "IterationStatus",
    "MessageType",
    "PRState",
    "ProcessingMode",
    "ReviewAction",
    "SettingType",
    "SidebarMode",
    "StageStatus",
    "StreamChunkType",
    "ValidationStepStatus",
    # Helper dataclasses
    "AgentMessage",
    "BranchValidation",
    "CodeContext",
    "CodeLocation",
    "ConfirmDialogConfig",
    "ErrorDialogConfig",
    "FixResult",
    "GitHubIssue",
    "InputDialogConfig",
    "IssueSelectionItem",
    "NavigationEntry",
    "PRInfo",
    "RefuelResultItem",
    "ReviewFinding",
    "ReviewFindingItem",
    "SettingDefinition",
    "SettingValue",
    "SettingsSection",
    "StatusCheck",
    "ToolCallInfo",
    "ValidationStep",
    "WorkflowHistoryEntry",
    "WorkflowStage",
    # Widget state models
    "AgentOutputState",
    "AgentStreamEntry",
    "LoopIterationItem",
    "LoopIterationState",
    "StreamingPanelState",
    "NavigationContext",
    "PRSummaryState",
    "ReviewFindingsState",
    "ValidationStatusState",
    "WorkflowProgressState",
    # Screen state models
    "ConfigOption",
    "ConfigScreenState",
    "HomeScreenState",
    "LogEntry",
    "LogPanelState",
    "NavigationItem",
    "RecentWorkflowEntry",
    "ReviewIssue",
    "ReviewScreenActionState",
    "ReviewScreenState",
    "ScreenState",
    "SettingsScreenState",
    "SidebarState",
    "StageState",
    "WorkflowScreenState",
    # Theme models
    "ACCENT_COLORS",
    "AccentColor",
    "DARK_THEME",
    "LIGHT_THEME",
    "THEMES",
    "ThemeColors",
    "ThemeManager",
    "ThemeMode",
    "ThemePreferences",
    "get_current_theme",
    "get_theme_manager",
]
